# Generated by Django 5.0.7 on 2024-11-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_cameraconfiguration_success_sound_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='student',
            name='phase',
            field=models.CharField(max_length=25),
        ),
    ]
